branch-defaults:
  backup-master:
    environment: null
    group_suffix: null
  dc3dd6c785af22dcf70d9cc087c96aa5bd82e5f3:
    environment: django-env
    group_suffix: null
  master:
    environment: django-env
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
