# Generated by Django 3.2.6 on 2021-12-06 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Real_estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(default='jonas Sievers', max_length=200)),
                ('charging_points_to_install', models.IntegerField(default=4)),
                ('charging_points_expandable', models.IntegerField(default=5)),
                ('house_connection_power', models.IntegerField(default=40)),
                ('property_type', models.CharField(choices=[('Einfamilienhaus', 'Einfamilienhaus'), ('Mehrfamilienhaus', 'Mehrfamilienhaus')], default='Einfamilienhaus', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
    ]
