# Generated by Django 3.2.6 on 2021-12-12 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_real_estate_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_profile', models.CharField(choices=[('20', '20 km/Tag'), ('40', '40 km/Tag'), ('60', '60 km/Tag'), ('100', '100 km/Tag')], default='40 km/Tag', max_length=200)),
                ('person', models.CharField(default='jonas Sievers', max_length=200)),
                ('cable_length', models.IntegerField(default=40)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='property_type',
            field=models.CharField(choices=[('Einfamilienhaus1', 'Einfamilienhaus'), ('Mehrfamilienhaus', 'Mehrfamilienhaus')], default='Einfamilienhaus', max_length=200),
        ),
    ]
