# Generated by Django 3.2.6 on 2021-12-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_charging_cable_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging',
            name='cable_length',
            field=models.CharField(choices=[('10', '10 m'), ('20', '20 m'), ('30', '30 m'), ('40', '40 m'), ('50', '50 m'), ('100', '100 m'), ('200', '200 m')], default='10', max_length=200),
        ),
    ]
