# Generated by Django 3.2.6 on 2021-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_charging_driving_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='charging',
            name='usage_years',
            field=models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40')], default='20', max_length=200),
        ),
    ]
