# Generated by Django 3.2.6 on 2021-12-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_charging_usage_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging',
            name='usage_years',
            field=models.CharField(choices=[('10', '10 Jahre'), ('20', '20 Jahre'), ('30', '30 Jahre'), ('40', '40 Jahre')], default='20', max_length=200),
        ),
    ]
