# Generated by Django 3.2.6 on 2021-12-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211219_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='property_type',
            field=models.CharField(choices=[('Einfamilienhaus', 'Einfamilienhaus'), ('Mehrfamilienhaus', 'Mehrfamilienhaus')], default='Einfamilienhaus', max_length=200),
        ),
    ]
