# Generated by Django 3.2.6 on 2021-12-22 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211221_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokal_Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_size', models.CharField(choices=[('20', '20 m2'), ('30', '30 m2'), ('40', '40 m2'), ('50', '50 m2'), ('60', '60 m2')], default='30', max_length=200)),
                ('solar_radiation', models.CharField(choices=[('1000', '1000 kWh/m2'), ('1100', '1100 kWh/ m2'), ('1200', '1200 kWh/m2'), ('1300', '1300 kWh/m2')], default='1100', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('person', models.CharField(default='jonas Sievers', max_length=200)),
            ],
        ),
    ]
