# Generated by Django 3.2.6 on 2021-12-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_lokal_energy_pv_kw_peak'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokal_energy',
            name='electricity_generation_year',
            field=models.IntegerField(default=4100),
        ),
    ]
