# Generated by Django 3.2.6 on 2022-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_lokal_energy_electricity_generation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokal_energy',
            name='roof_orientation',
            field=models.CharField(choices=[('Süd', 'Süd'), ('Süd-West/ Süd-Ost', 'Süd-West/ Süd-Ost'), ('West/ Ost', 'West/ Ost'), ('Nord-West/ Nord-Ost', 'Nord-West/ Nord-Ost'), ('Nord', 'Nord')], default='Süd', max_length=200),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='roof_tilt',
            field=models.CharField(choices=[('0', '0°'), ('15', '15°'), ('30', '30°'), ('45', '45°')], default='30', max_length=200),
        ),
    ]
