# Generated by Django 3.2.6 on 2022-01-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220105_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='number_persons',
            field=models.CharField(choices=[('1 Person', '1 Person'), ('2 Personen', '2 Personen'), ('3 Personen', '3 Personen'), ('4 Personen', '4 Personen'), ('> 4 Personen', '> 4 Personen')], default='2 Personen', max_length=200),
        ),
        migrations.AddField(
            model_name='real_estate',
            name='water_heating',
            field=models.CharField(choices=[('ohne Strom', 'ohne Strom'), ('mit Strom', 'mit Strom')], default='mit Strom', max_length=200),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='property_type',
            field=models.CharField(choices=[('Haus', 'Haus'), ('Wohnung', 'Wohnung')], default='Haus', max_length=200),
        ),
    ]
