# Generated by Django 3.2.6 on 2022-01-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220106_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='electricity_consumption_year',
            field=models.IntegerField(default=3800),
        ),
    ]
