# Generated by Django 3.2.6 on 2022-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_real_estate_electricity_consumption_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_1KWpeak_Total_ernnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_1KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_1KWpeak_investment_cost',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_1KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_2KWpeak_Total_ernnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_2KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_2KWpeak_investment_cost',
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_2KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_3KWpeak_Total_ernnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_3KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_3KWpeak_investment_cost',
            field=models.IntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_3KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_4KWpeak_Total_ernnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_4KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_4KWpeak_investment_cost',
            field=models.IntegerField(default=8000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_4KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='roof_size',
            field=models.CharField(choices=[('7', '7 m2'), ('14', '14 m2'), ('20', '20 m2'), ('30', '30 m2'), ('40', '40 m2'), ('50', '50 m2'), ('60', '60 m2')], default='30', max_length=200),
        ),
    ]
