# Generated by Django 3.2.6 on 2022-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220107_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lokal_energy',
            name='pv_1KWpeak_Total_ernnings',
        ),
        migrations.RemoveField(
            model_name='lokal_energy',
            name='pv_2KWpeak_Total_ernnings',
        ),
        migrations.RemoveField(
            model_name='lokal_energy',
            name='pv_3KWpeak_Total_ernnings',
        ),
        migrations.RemoveField(
            model_name='lokal_energy',
            name='pv_4KWpeak_Total_ernnings',
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='pv_1KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='pv_1KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='pv_2KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='pv_2KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='pv_3KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='pv_3KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=4500),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='pv_4KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='pv_4KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=7000),
        ),
    ]
