# Generated by Django 3.2.6 on 2022-01-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220107_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_10KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_10KWpeak_investment_cost',
            field=models.IntegerField(default=20000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_10KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=7000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_5KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_5KWpeak_investment_cost',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_5KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=7000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_6KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_6KWpeak_investment_cost',
            field=models.IntegerField(default=12000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_6KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=7000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_7KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_7KWpeak_investment_cost',
            field=models.IntegerField(default=14000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_7KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=7000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_8KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_8KWpeak_investment_cost',
            field=models.IntegerField(default=16000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_8KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=7000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_9KWpeak_earnings_sold_electricity',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_9KWpeak_investment_cost',
            field=models.IntegerField(default=18000),
        ),
        migrations.AddField(
            model_name='lokal_energy',
            name='pv_9KWpeak_saved_costs_own_electricity',
            field=models.IntegerField(default=7000),
        ),
    ]
