# Generated by Django 3.2.6 on 2022-01-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220107_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='real_estate',
            name='charging_points_expandable',
        ),
    ]
