# Generated by Django 3.2.6 on 2022-01-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_real_estate_charging_points_expandable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='house_connection_power',
            field=models.IntegerField(default=43),
        ),
    ]
