# Generated by Django 3.2.6 on 2022-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_real_estate_house_connection_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='number_properties',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('10', '10'), ('20', '20'), ('30', '30')], default='1', max_length=200),
        ),
    ]
