# Generated by Django 3.2.6 on 2022-01-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_real_estate_number_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='property_type',
            field=models.CharField(choices=[('Haus', 'Haus'), ('Wohnung', 'Wohnung')], max_length=200),
        ),
    ]
