# Generated by Django 3.2.6 on 2022-01-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_real_estate_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='property_type',
            field=models.CharField(choices=[('Haus', 'Haus'), ('Wohnung', 'Wohnung')], default=None, max_length=200),
        ),
    ]
