# Generated by Django 3.2.6 on 2022-01-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_real_estate_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='arrival_time',
            field=models.CharField(choices=[('1', 'Home Office'), ('15', '15 Uhr'), ('16', '16 Uhr'), ('17', '17 Uhr'), ('18', '18 Uhr'), ('19', '19 Uhr'), ('20', '20 Uhr')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='cable_length',
            field=models.CharField(choices=[('10', '10 m'), ('20', '20 m'), ('30', '30 m'), ('40', '40 m'), ('50', '50 m'), ('100', '100 m'), ('200', '200 m')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='departure_time',
            field=models.CharField(choices=[('23', 'Home Office'), ('4', '4 Uhr'), ('5', '5 Uhr'), ('6', '6 Uhr'), ('7', '7 Uhr'), ('8', '8 Uhr'), ('9', '9 Uhr')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='driving_profile',
            field=models.CharField(choices=[('20', '20 km/Tag'), ('40', '40 km/Tag'), ('60', '60 km/Tag'), ('100', '100 km/Tag')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='number_persons',
            field=models.CharField(choices=[('1 Person', '1 Person'), ('2 Personen', '2 Personen'), ('3 Personen', '3 Personen'), ('4 Personen', '4 Personen'), ('> 4 Personen', '> 4 Personen')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='number_properties',
            field=models.CharField(choices=[('1', '1'), ('5', '5'), ('10', '10'), ('20', '20'), ('30', '30')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='usage_years',
            field=models.CharField(choices=[('10', '10 Jahre'), ('20', '20 Jahre'), ('30', '30 Jahre'), ('40', '40 Jahre')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='water_heating',
            field=models.CharField(choices=[('ohne Strom', 'ohne Strom'), ('mit Strom', 'mit Strom')], default=None, max_length=200),
        ),
    ]
