# Generated by Django 3.2.6 on 2022-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220112_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokal_energy',
            name='roof_orientation',
            field=models.CharField(choices=[('Süd', 'Süd'), ('Süd-West/ Süd-Ost', 'Süd-West/ Süd-Ost'), ('West/ Ost', 'West/ Ost'), ('Nord-West/ Nord-Ost', 'Nord-West/ Nord-Ost'), ('Nord', 'Nord')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='roof_size',
            field=models.CharField(choices=[('7', '7 m2'), ('14', '14 m2'), ('20', '20 m2'), ('30', '30 m2'), ('40', '40 m2'), ('50', '50 m2'), ('60', '60 m2')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='roof_tilt',
            field=models.CharField(choices=[('0', '0°'), ('15', '15°'), ('30', '30°'), ('45', '45°')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='solar_radiation',
            field=models.CharField(choices=[('1000', '1000 kWh/m2'), ('1100', '1100 kWh/ m2'), ('1200', '1200 kWh/m2'), ('1300', '1300 kWh/m2')], default=None, max_length=200),
        ),
    ]
