# Generated by Django 3.2.6 on 2022-01-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220112_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokal_energy',
            name='roof_size',
            field=models.CharField(choices=[('7', '7 m&#178'), ('14', '14 m&#178'), ('20', '20 m&#178'), ('30', '30 m&#178'), ('40', '40 m&#178'), ('50', '50 m&#178'), ('60', '60 m&#178')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='solar_radiation',
            field=models.CharField(choices=[('1000', '1000 kWh/m&#178'), ('1100', '1100 kWh/ m&#178'), ('1200', '1200 kWh/m&#178'), ('1300', '1300 kWh/m&#178')], default=None, max_length=200),
        ),
    ]
