# Generated by Django 3.2.6 on 2022-01-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_lokal_energy_roof_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokal_energy',
            name='roof_size',
            field=models.CharField(choices=[('7', '7'), ('14', '14'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='lokal_energy',
            name='solar_radiation',
            field=models.CharField(choices=[('1000', '1000'), ('1100', '1100'), ('1200', '1200'), ('1300', '1300')], default=None, max_length=200),
        ),
    ]
