# Generated by Django 3.2.6 on 2022-01-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220112_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='real_estate',
            name='arrival_time',
            field=models.CharField(choices=[('Home Office', 'Home Office'), ('15', '15 Uhr'), ('16', '16 Uhr'), ('17', '17 Uhr'), ('18', '18 Uhr'), ('19', '19 Uhr'), ('20', '20 Uhr')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='real_estate',
            name='departure_time',
            field=models.CharField(choices=[('Home Office', 'Home Office'), ('4', '4 Uhr'), ('5', '5 Uhr'), ('6', '6 Uhr'), ('7', '7 Uhr'), ('8', '8 Uhr'), ('9', '9 Uhr')], default=None, max_length=200),
        ),
    ]
