# Generated by Django 3.2.6 on 2022-01-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_lokal_energy_battery_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokal_energy',
            name='battery_capacity',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('3', '3'), ('5', '5'), ('7', '7'), ('10', '10'), ('14', '14')], default=None, max_length=200),
        ),
    ]
